### ISSUE TITLE
Is it supposed to work on AGP 4.1?

### ISSUE THREAD

**Issue by LouisCAD** [GradleUp/auto-manifest#2]
Hello,

I'm using AGP 4.1-rc02 and I get the following error in a leaf Android module:
```
Caused by: com.android.builder.errors.EvalIssueException: Manifest file does not exist:
```

I have the following configuration in the root project's `build.gradle.kts`:

```.gradle.kts
plugins {
    id("com.gradleup.auto.manifest") version "1.0.2"
}

autoManifest {
    packageName.set("com.company")
    replaceDashesWithDot.set(true)
}
```

I see the plugin has been built with AGP 3.6.3. Did you ever try it in a project using AGP 4.1? Might be caused by a change in ordering in recent AGP versions?

**Comment by tasomaniac** [comment]
While working on this AGP 4.1 was early alpha and it was working. I didn't check with RCs.

I actually want to use the new transformation APIs available in 4.1 but they did not quite work at the time. Actually I heard in Slack that the API is going to break in 4.2 and 5.0.

Anyways, thanks for reporting this. I will have a look soon.

**Comment by LouisCAD** [comment]
Thanks for your response and consideration!

FYI, I have been trying with AGP 4.1-rc02 but in AS 4.2 Canary 10.
I don't think that should change the behavior, but in case you are not reproducing in AS 4.1 RC2/3, then this might be good to know.

**Comment by tasomaniac** [comment]
Hey, sorry for late reply on this. I found one issue and going to push a fix for that.

I was not able to reproduce this error on the sample app. I will try in Splitties.

**Comment by tasomaniac** [comment]
I think the issue on Splitties was because of the following line: https://github.com/LouisCAD/Splitties/blob/main/buildSrc/src/main/kotlin/config/AndroidLibraryConfig.kt#L27

**Comment by tasomaniac** [comment]
For those who are curious, I've integrated it into Splitties. This library is even more useful for Kotlin Multiplatform projects (Splitties is one of them) since you have to put the manifest under `main` folder which is not really a valid folder at all in Kotlin Multiplatform. 

Splitties was changing it manually to be consistent with `androidMain` in KMM. It is mostly not needed anymore.

Checkout the PR for more details: https://github.com/LouisCAD/Splitties/pull/260

**Comment by LouisCAD** [comment]
Thanks for digging @tasomaniac!
Do you know if the plugin could play nicely with custom defined manifest files, or if it could detect it and show a proper error message with resolution suggestion?

**Comment by tasomaniac** [comment]
It's tricky. What I can do is to hardcore the original path used by Android Gradle Plugin and compare. AGP does not have any API on this and if they change it, my plugin would be broken. But the fact is that it did not change in 10 years 😊

**Comment by tasomaniac** [comment]
I gave another thought on this.

If you have custom defined manifest file and that file exists, the plugin already detects that and it wouldn't be a problem.

The problem with Splitties was that the custom path for Manifest was defined for all modules. When integrating `auto-manifest`,  since the natural thing to do is to delete those one-liner files, it was erroring.

Not sure if we can handle that. I will add info into Readme tho.
